version: 2.1

orbs:
  node: circleci/node@5

jobs:

  install:
    executor:
      name: node/default
      tag: "22.14"
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  test:
    executor:
      name: node/default
      tag: "22.14"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Tests
          command: npm test -- --watchAll=false --passWithNoTests

  security-scan:
    executor:
      name: node/default
      tag: "22.14"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Dependency Vulnerability Scan
          command: npm audit --audit-level=high || true

  sonar-scan:
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      - run:
          name: SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=payment-portal \
              -Dsonar.sources=src \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.login=$SONAR_TOKEN

  build:
    executor:
      name: node/default
      tag: "22.14"
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Build React App
          command: npm run build
      - run:
          name: Create Artifacts
          command: mkdir -p ~/artifacts
      - run:
          name: Copy Build Files
          command: cp -R build ~/artifacts
      - store_artifacts:
          path: ~/artifacts
          destination: build-output

workflows:
  devsecops-pipeline:
    jobs:
      - install
      - test:
          requires:
            - install
      - security-scan:
          requires:
            - install
      - sonar-scan:
          requires:
            - test
      - build:
          requires:
            - test
<<<<<<< HEAD
            - security-scan
=======
            - security-scan
>>>>>>> 332b382 (Mock Firebase components in tests)
